kind: pipeline
type: docker
name: hello-world

steps:
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: pavansa/docker-hello-world
    username:
      from_secret: pavansa
    password:
      from_secret: docker_password
    tags: 
      - latest
